# proto-file: agent_based_epidemic_sim/applications/home_work/config.proto
# proto-message: HomeWorkSimulationConfig


init_time {
}

population_size: 10000
agent_properties {
  ptts_transition_model {
    state_transition_diagram {
      health_state: EXPOSED
      transition_probability {
        health_state: INFECTIOUS
        transition_probability: 0.8
        mean_days_to_transition: 2
        sd_days_to_transition: 2
      }
      transition_probability {
        health_state: RECOVERED
        transition_probability: 0.2
        mean_days_to_transition: 2
        sd_days_to_transition: 2
      }
    }
    state_transition_diagram {
      health_state: INFECTIOUS
      transition_probability {
        health_state: RECOVERED
        transition_probability: 1
        mean_days_to_transition: 10
        sd_days_to_transition: 10
      }
    }
  }
  departure_distribution {
    mean: .3
    stddev: .3
  }
  work_duration_distribution {
    mean: .3
    stddev: .3
  }
  arrival_distribution {
    mean: .3
    stddev: .3
  }
  initial_health_state_distribution {
    buckets {
      proto_value { [type.googleapis.com/abesim.HealthState] { state: SUSCEPTIBLE } }
      count: .9
    }
    buckets {
      proto_value { [type.googleapis.com/abesim.HealthState] { state: INFECTIOUS } }
      count: .1
    }
  }
}
location_distributions {
  business_distribution {
    alpha: 0.5
    beta: 1000
  }
  household_size_distribution {
    buckets {
      int_value: 1
      count: 0.1
    }
    buckets {
      int_value: 2
      count: 0.2
    }
    buckets {
      int_value: 3
      count: 0.2
    }
    buckets {
      int_value: 4
      count: 0.4
    }
    buckets {
      int_value: 5
      count: 0.1
    }
  }
}
transmissibility: .95
distancing_policy {
  stages {
    start_time {
      seconds: 1728000
    }
    essential_worker_fraction: 0.2
  }
  stages {
    start_time {
      seconds: 5184000
    }
    essential_worker_fraction: 1.0
  }
}
step_size {
  seconds: 86400
}
num_steps: 100
