# Utililites for pandemic package.

licenses(["notice"])

package(default_visibility = [
    "//agent_based_epidemic_sim:internal",
])

cc_library(
    name = "ostream_overload",
    hdrs = ["ostream_overload.h"],
)
