state_transition_diagram {
  health_state: SUSCEPTIBLE
  transition_probability {
    health_state: SUSCEPTIBLE
    transition_probability: 1
  }
  transition_probability {
    health_state: EXPOSED
    transition_probability: 0
  }
  transition_probability {
    health_state: INFECTIOUS
    transition_probability: 0
  }
  transition_probability {
    health_state: RECOVERED
    transition_probability: 0
  }
  rate: 1
}
state_transition_diagram {
  health_state: EXPOSED
  transition_probability {
    health_state: SUSCEPTIBLE
    transition_probability: 0
  }
  transition_probability {
    health_state: EXPOSED
    transition_probability: 0
  }
  transition_probability {
    health_state: INFECTIOUS
    transition_probability: 0.8
  }
  transition_probability {
    health_state: RECOVERED
    transition_probability: 0.2
  }
  rate: 0.5
}
state_transition_diagram {
  health_state: INFECTIOUS
  transition_probability {
    health_state: SUSCEPTIBLE
    transition_probability: 1
  }
  transition_probability {
    health_state: EXPOSED
    transition_probability: 0
  }
  transition_probability {
    health_state: INFECTIOUS
    transition_probability: 0
  }
  transition_probability {
    health_state: RECOVERED
    transition_probability: 1
  }
  rate: 0.2
}
state_transition_diagram {
  health_state: RECOVERED
  transition_probability {
    health_state: SUSCEPTIBLE
    transition_probability: 0
  }
  transition_probability {
    health_state: EXPOSED
    transition_probability: 0
  }
  transition_probability {
    health_state: INFECTIOUS
    transition_probability: 0
  }
  transition_probability {
    health_state: RECOVERED
    transition_probability: 1
  }
  rate: 1
}
